version: "3.8"

services:
  backend:
    container_name: backend
    build: backend/
    command: bash -c "alembic -c backend/alembic.ini -x data=true upgrade head && uvicorn backend.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - 8080:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
volumes:
  caddy-data:
  caddy-config:
